//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamelaFundacionFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Becado
    {
        public Becado()
        {
            this.Horario = new HashSet<Horario>();
            this.HorasReportadas = new HashSet<HorasReportadas>();
        }
    
        public int Becado_ID { get; set; }
        public int Tutor_ID { get; set; }
        public int Escuela_ID { get; set; }
        public int Organizacion_ID { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Edad { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Categoria { get; set; }
        public double Promedio { get; set; }
        public int Horas { get; set; }
        public string Actividad { get; set; }
    
        public virtual Escuela Escuela { get; set; }
        public virtual Mensualidades Mensualidades { get; set; }
        public virtual Organizacion Organizacion { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual ICollection<HorasReportadas> HorasReportadas { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
