//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamelaFundacionFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beca
    {
        public string Categoria { get; set; }
        public int Escuela_ID { get; set; }
        public string Beca1 { get; set; }
        public int Horas { get; set; }
    
        public virtual Escuela Escuela { get; set; }
    }
}
