//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamelaFundacionFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuela
    {
        public Escuela()
        {
            this.Beca = new HashSet<Beca>();
            this.Becado = new HashSet<Becado>();
        }
    
        public int Escuela_ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<Beca> Beca { get; set; }
        public virtual ICollection<Becado> Becado { get; set; }
    }
}
