//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamelaFundacionFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasReportadas
    {
        public int Becario_ID { get; set; }
        public int HorasTotal { get; set; }
        public Nullable<int> Mensualidad1 { get; set; }
        public Nullable<int> Mensualidad2 { get; set; }
        public Nullable<int> Mensualidad3 { get; set; }
        public Nullable<int> Mensualidad4 { get; set; }
        public Nullable<int> Mensualidad5 { get; set; }
    
        public virtual Becado Becado { get; set; }
    }
}
