//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamelaFundacionFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensualidades
    {
        public Mensualidades()
        {
            this.Becado = new HashSet<Becado>();
        }
    
        public string Categoria { get; set; }
        public int Beca { get; set; }
        public Nullable<int> Mensualidad1 { get; set; }
        public Nullable<int> Mensualidad2 { get; set; }
        public Nullable<int> Mensualidad3 { get; set; }
        public Nullable<int> Mensualidad4 { get; set; }
        public Nullable<int> Mensualidad5 { get; set; }
    
        public virtual ICollection<Becado> Becado { get; set; }
    }
}
