//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamelaFundacionFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizacion
    {
        public Organizacion()
        {
            this.Becado = new HashSet<Becado>();
            this.Horario = new HashSet<Horario>();
        }
    
        public int Organizacion_ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
    
        public virtual ICollection<Becado> Becado { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
