//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamelaFundacionFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int Becado_ID { get; set; }
        public string Categoria { get; set; }
        public int Total { get; set; }
        public Nullable<int> Mensualidad1 { get; set; }
        public Nullable<bool> Mensualidad1_pag { get; set; }
        public Nullable<int> Mensualidad2 { get; set; }
        public Nullable<bool> Mensualidad2_pag { get; set; }
        public Nullable<int> Mensualidad3 { get; set; }
        public Nullable<bool> Mensualidad3_pag { get; set; }
        public Nullable<int> Mensualidad4 { get; set; }
        public Nullable<bool> Mensualidad4_pag { get; set; }
        public Nullable<int> Mensualidad5 { get; set; }
        public Nullable<bool> Mensualidad5_pag { get; set; }
    
        public virtual Becado Becado { get; set; }
    }
}
